# Generated by Django 2.2 on 2019-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contet', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
